name: 'Anaconda Build and Publish'
description: 'Build and Publish conda package'
author: 'Andrew Prokhorenkov, Maxime Borry, Thomas Arsouze'
branding:
  icon: 'package'  
  color: 'purple'
inputs:
  condaDir:
    description: 'Directory with conda recipe. Default . .'
    required: false
    default: '.'
  anacondaToken:
    description: 'Anaconda access Token (required)'
    required: true
  channels:
    description: 'Optional Extra anaconda channels to use. Default conda-forge.'
    required: false
    default: 'conda-forge'
  publishChannel:
    description: 'Optional Channel to publish the anaconda package. Default conda-forge.'
    required: false
    default: 'conda-forge'
runs:
  using: 'docker'
  image: 'Dockerfile'
