name: 'Publish Conda package to Anaconda.org'
description: 'Build and Publish conda package to Anaconda'
author: 'Andrew Prokhorenkov, Maxime Borry, Thomas Arsouze'
branding:
  icon: 'package'  
  color: 'purple'
inputs: 
  condaDir:
    description: 'Directory with conda recipe'
    default: '.'
  anacondaToken:
    description: 'Optional Anaconda access Token'
  channels:
    description: 'Optional Extra anaconda channels to use'
    default: 'conda-forge'
  publishChannel:
    description: 'Optional Channel to publish the anaconda package'
    default: 'conda-forge'
runs:
  using: 'docker'
  image: 'Dockerfile'
